x = 0:0.1:360;
subplot(2, 2, 1);
plot(sind(x));
title('Sin');
subplot(2, 2, 2);
plot(cosd(x));
title('Cos');
subplot(2, 2, 3);
plot(tand(x));
title('Tan');
subplot(2, 2, 4);
plot(cotd(x));
title('Cot');