function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Task1"};
	this.sidHashMap["Task1"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Task1:2"};
	this.sidHashMap["Task1:2"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Task1:7"};
	this.sidHashMap["Task1:7"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "Task1:11"};
	this.sidHashMap["Task1:11"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Task1:19"};
	this.sidHashMap["Task1:19"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Display1"] = {sid: "Task1:18"};
	this.sidHashMap["Task1:18"] = {rtwname: "<Root>/Display1"};
	this.rtwnameHashMap["<Root>/Merge"] = {sid: "Task1:15"};
	this.sidHashMap["Task1:15"] = {rtwname: "<Root>/Merge"};
	this.rtwnameHashMap["<Root>/Switch Case"] = {sid: "Task1:1"};
	this.sidHashMap["Task1:1"] = {rtwname: "<Root>/Switch Case"};
	this.rtwnameHashMap["<Root>/Switch Case Action Subsystem"] = {sid: "Task1:2"};
	this.sidHashMap["Task1:2"] = {rtwname: "<Root>/Switch Case Action Subsystem"};
	this.rtwnameHashMap["<Root>/Switch Case Action Subsystem1"] = {sid: "Task1:7"};
	this.sidHashMap["Task1:7"] = {rtwname: "<Root>/Switch Case Action Subsystem1"};
	this.rtwnameHashMap["<Root>/Switch Case Action Subsystem2"] = {sid: "Task1:11"};
	this.sidHashMap["Task1:11"] = {rtwname: "<Root>/Switch Case Action Subsystem2"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Task1:16"};
	this.sidHashMap["Task1:16"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/Action Port"] = {sid: "Task1:4"};
	this.sidHashMap["Task1:4"] = {rtwname: "<S1>/Action Port"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "Task1:6"};
	this.sidHashMap["Task1:6"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "Task1:5"};
	this.sidHashMap["Task1:5"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/Action Port"] = {sid: "Task1:8"};
	this.sidHashMap["Task1:8"] = {rtwname: "<S2>/Action Port"};
	this.rtwnameHashMap["<S2>/Constant"] = {sid: "Task1:9"};
	this.sidHashMap["Task1:9"] = {rtwname: "<S2>/Constant"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "Task1:10"};
	this.sidHashMap["Task1:10"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>/Action Port"] = {sid: "Task1:12"};
	this.sidHashMap["Task1:12"] = {rtwname: "<S3>/Action Port"};
	this.rtwnameHashMap["<S3>/Constant"] = {sid: "Task1:13"};
	this.sidHashMap["Task1:13"] = {rtwname: "<S3>/Constant"};
	this.rtwnameHashMap["<S3>/Out1"] = {sid: "Task1:14"};
	this.sidHashMap["Task1:14"] = {rtwname: "<S3>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
